[package]
name = "wasm_swirl"
version = "0.1.0"
authors = ["Orion Kindel <cakekindel@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.67"
streaming-iterator = "0.1.5"
js-sys = "0.3.44"
console_error_panic_hook = "0.1.6"
